# Generated by Django 5.1.2 on 2025-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_contact_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contact',
        ),
        migrations.AddField(
            model_name='chat',
            name='contact',
            field=models.ManyToManyField(to='chat.contacts'),
        ),
    ]
