# Generated by Django 5.1.2 on 2025-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
        ('main', '0003_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='contacts',
            field=models.ManyToManyField(related_name='chat_contacts', to='main.contacts'),
        ),
    ]
