# Generated by Django 5.1.2 on 2025-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='picture',
            field=models.ImageField(blank=True, default='chat_picture/default.jpg', upload_to='chat_picture/'),
        ),
    ]
