# Generated by Django 5.1.2 on 2025-03-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
